name: detectify_ai
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:

  provider: ^6.1.2

  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.2.0

  # Image picking
  image_picker: ^1.0.7

  # File picking (audio & video)
  file_picker: ^8.0.0

  # UI icons
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
